<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Python - Lab 1

In [4]:
# print the student list
# create a list of students' names
students = ['Alice', 'Bob', 'Pradeep', 'Jasmine', 'Joseph', 'Aris', 'Yana', 'Jane', 'Emily', 'Antoni']
print(f'Student list: {students}')

Student list: ['Alice', 'Bob', 'Pradeep', 'Jasmine', 'Joseph', 'Aris', 'Yana', 'Jane', 'Emily', 'Antoni']

In [5]:
# this is a comment
a = 100
a = a + 200
print(f"{20*'#'}")
print (f"The type of variable a: {a+400}")

####################
The type of variable a: 700

In [6]:
# print the list of students one student in a line with its index
for i, student in enumerate(students):
    print(f'Index {i+1:02d} \t {student}')

Index 01 	 Alice
Index 02 	 Bob
Index 03 	 Pradeep
Index 04 	 Jasmine
Index 05 	 Joseph
Index 06 	 Aris
Index 07 	 Yana
Index 08 	 Jane
Index 09 	 Emily
Index 10 	 Antoni

In [7]:
# print the list of students in reverse order one student in a line with its index
students_reversed = students.copy()
students_reversed.reverse()
for i, student in enumerate(students_reversed):
    print(f'Index {i+1:02d} \t {student}')

Index 01 	 Antoni
Index 02 	 Emily
Index 03 	 Jane
Index 04 	 Yana
Index 05 	 Aris
Index 06 	 Joseph
Index 07 	 Jasmine
Index 08 	 Pradeep
Index 09 	 Bob
Index 10 	 Alice

In [8]:
# print the student list in random order
# hint look up the function random.sample

In [9]:
# list students in order of their exam marks in the following list
marks = [87,45,76,64,66,90,55,73,69,75]
studentsAndMarks = dict(zip(students, marks))

def value_getter(item):
  return item[0]

print(f"Students and their marks: \n {studentsAndMarks}")
for student in sorted(studentsAndMarks, key=studentsAndMarks.get, reverse=True ):
  print(f"{student:10s}:{studentsAndMarks[student]}")

print(student , studentsAndMarks[student])
print()
print(studentsAndMarks.get)

Students and their marks:
 {'Alice': 87, 'Bob': 45, 'Pradeep': 76, 'Jasmine': 64, 'Joseph': 66, 'Aris': 90, 'Yana': 55, 'Jane': 73, 'Emily': 69, 'Antoni': 75}
Aris      :90
Alice     :87
Pradeep   :76
Antoni    :75
Jane      :73
Emily     :69
Joseph    :66
Jasmine   :64
Yana      :55
Bob       :45
Bob 45

<built-in method get of dict object at 0x7e66276c2040>

In [10]:
# Extension: Keep only students who have a mark above 60

studentsAbove60 = dict()

for student in studentsAndMarks.keys():
    if studentsAndMarks[student] > 60:
        studentsAbove60[student] = studentsAndMarks[student]

for student in sorted(studentsAbove60, key=studentsAbove60.get, reverse=True):
  print(f"{student:10s}:{studentsAbove60[student]}")

Aris      :90
Alice     :87
Pradeep   :76
Antoni    :75
Jane      :73
Emily     :69
Joseph    :66
Jasmine   :64



---



---



> > > > > > > > > Â© 2023 Institute of Data


---



---